<?php
require_once "config.php";
requireLogin();
if(!allowed(['admin','dean'])){http_response_code(403);die("Access denied.");}
$dashboardLink = user()['home'] ?? 'index.php';
if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $idNo = trim((string)($_POST['id_no'] ?? ''));
    if ($idNo === '') {
        $idNo = generateStudentIdNumber($pdo, isset($_POST['course_id']) && $_POST['course_id'] !== '' ? (int)$_POST['course_id'] : null);
    }
    $stmt=$pdo->prepare("INSERT INTO students(id_no,name,course_id,status) VALUES(?,?,?,?)");
    $stmt->execute([$idNo, trim($_POST['name']), $_POST['course_id'] !== '' ? $_POST['course_id'] : null, $_POST['status']]);
    header("Location: students.php?added=1"); exit;
}
$courses=$pdo->query("SELECT course_id,course_code,course_name FROM courses WHERE status='active' ORDER BY course_name")->fetchAll();
$students=$pdo->query("SELECT s.*,c.course_code,c.course_name,d.department_name FROM students s LEFT JOIN courses c ON c.course_id=s.course_id LEFT JOIN departments d ON d.department_id=c.department_id ORDER BY s.student_id DESC")->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Students | College ERP</title><link rel="stylesheet" href="assets/css/style.css"><style>
.modal{position:fixed;inset:0;display:none;align-items:center;justify-content:center;background:rgba(15,23,42,.45);padding:20px;z-index:1000}.modal.show,.modal.active{display:flex}.modal-box{background:#fff;border-radius:12px;max-width:560px;width:100%;box-shadow:0 20px 45px rgba(15,23,42,.25);overflow:hidden}.modal-head{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;border-bottom:1px solid #e2e8f0}.modal-head button{border:0;background:transparent;font-size:22px;cursor:pointer;color:#475569}.modal-box form{padding:20px;display:grid;gap:14px}.modal-box label{font-weight:700;color:#334155;font-size:13px}.modal-box input,.modal-box select{width:100%;box-sizing:border-box;padding:10px 12px;border:1px solid #cbd5e1;border-radius:6px;margin-top:6px}.modal-actions{display:flex;justify-content:flex-end;gap:10px;padding-top:8px}.primary,.secondary{border:0;border-radius:6px;padding:10px 16px;font-weight:700;cursor:pointer}.primary{background:#1e3d73;color:#fff}.secondary{background:#e2e8f0;color:#1e293b}
</style></head><body>
<div class="app"><aside class="sidebar"><?php include "partials/sidebar.php"; ?></aside><main class="main"><header class="topbar"><button class="menu">☰</button><div class="search">⌕ <input placeholder="Search students..."></div><div class="top-actions"><div class="avatar"><?= strtoupper(substr(user()['name'] ?? 'ERP', 0, 2)) ?></div><div><strong><?= htmlspecialchars(user()['name'] ?? 'ERP User') ?></strong><small><?= htmlspecialchars(ucfirst((user()['role'] ?? 'admin'))) ?></small></div></div></header>
<section class="content"><div class="page-head"><div><a href="<?=htmlspecialchars($dashboardLink)?>" style="display:inline-block;margin-bottom:12px;color:#174a9b;font-size:13px;font-weight:700;">← Back to dashboard</a><p class="eyebrow">STUDENT MANAGEMENT</p><h1>Student Registry</h1><p>Manage enrolled students and their course assignments.</p></div><button class="primary" onclick="openModal()">＋ Add Student</button></div>
<?php if(isset($_GET['added'])): ?><div class="alert success">Student added successfully.</div><?php endif; ?>
<section class="card"><div class="toolbar"><div class="searchbox">⌕ <input id="studentSearch" onkeyup="filterTable('studentSearch','studentTable')" placeholder="Search by name, ID or course"></div><select><option>All statuses</option><option>Active</option><option>Graduated</option><option>Withdrawn</option></select></div>
<div class="table-wrap"><table id="studentTable"><thead><tr><th>ID No.</th><th>Student</th><th>Department</th><th>Course</th><th>Status</th><th>Joined</th><th></th></tr></thead><tbody>
<?php foreach($students as $s): ?><tr><td><b><?= htmlspecialchars($s['id_no']) ?></b></td><td><?= htmlspecialchars($s['name']) ?></td><td><?= htmlspecialchars($s['department_name'] ?? 'Pending') ?></td><td><b><?= htmlspecialchars($s['course_code'] ?? 'Pending') ?></b><small><?= htmlspecialchars($s['course_name'] ?? 'Course not assigned') ?></small></td><td><span class="status <?= $s['status'] ?>"><?= ucfirst($s['status']) ?></span></td><td><?= date('d M Y',strtotime($s['created_at'])) ?></td><td>⋮</td></tr><?php endforeach; ?>
<?php if(!$students): ?><tr><td colspan="7" class="empty">No students found.</td></tr><?php endif; ?></tbody></table></div></section>
</section></main></div>
<div class="modal" id="studentModal"><div class="modal-box"><div class="modal-head"><h2>Add Student</h2><button type="button" onclick="closeModal()">×</button></div><form method="post"><label>Student ID Number<input name="id_no" placeholder="Leave blank to auto-generate"></label><label>Full Name<input name="name" required></label><label>Course<select name="course_id" required><option value="">Select course</option><?php foreach($courses as $c): ?><option value="<?= $c['course_id'] ?>"><?= htmlspecialchars($c['course_code'].' — '.$c['course_name']) ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="active">Active</option><option value="graduated">Graduated</option><option value="withdrawn">Withdrawn</option></select></label><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button type="submit" class="primary">Save Student</button></div></form></div></div><script src="assets/js/app.js"></script></body></html>