<?php
require_once "../config.php";
requireLogin();
if(!allowed(['finance','admin'])){http_response_code(403);die("Access denied.");}
$dashboardLink='../'.user()['home'];
$channelSummary=$pdo->query("SELECT payment_method,COUNT(*) AS tx_count,COALESCE(SUM(amount_paid),0) AS total_amount FROM fee_payments GROUP BY payment_method ORDER BY total_amount DESC")->fetchAll();
$expenseSummary=$pdo->query("SELECT category,COUNT(*) AS voucher_count,COALESCE(SUM(amount),0) AS total_spent FROM expenses GROUP BY category ORDER BY total_spent DESC")->fetchAll();
$debtors=$pdo->query("SELECT s.id_no,s.name,c.course_code,COALESCE(b.total_billed,0) AS total_billed,COALESCE(p.total_paid,0) AS total_paid FROM students s JOIN courses c ON c.course_id=s.course_id LEFT JOIN (SELECT s2.student_id,SUM(fs.amount) AS total_billed FROM students s2 JOIN fee_structure fs ON fs.course_id=s2.course_id GROUP BY s2.student_id) b ON b.student_id=s.student_id LEFT JOIN (SELECT student_id,SUM(amount_paid) AS total_paid FROM fee_payments GROUP BY student_id) p ON p.student_id=s.student_id WHERE s.status='active' AND COALESCE(b.total_billed,0)>COALESCE(p.total_paid,0) ORDER BY (COALESCE(b.total_billed,0)-COALESCE(p.total_paid,0)) DESC")->fetchAll();
$grandRevenue=(float)$pdo->query("SELECT COALESCE(SUM(amount_paid),0) FROM fee_payments")->fetchColumn();
$grandExpenses=(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM expenses")->fetchColumn();
$netCashFlow=$grandRevenue-$grandExpenses;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Financial Reports | College ERP</title><link rel="stylesheet" href="../assets/css/style.css"><style>
.report-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:24px}.back-link{display:inline-block;margin-bottom:12px;color:#174a9b;font-size:13px;font-weight:700}.report-head h1{margin:0}.report-head p{color:#78849a}.report-actions{display:flex;gap:10px}.print-button{border:0;border-radius:7px;padding:11px 16px;background:#174a9b;color:#fff;font-weight:700;cursor:pointer}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px}.summary-card,.report-card{background:#fff;border:1px solid #e4e9f1;border-radius:8px;padding:20px}.summary-card span{font-size:11px;text-transform:uppercase;color:#78849a;font-weight:700}.summary-card strong{display:block;margin-top:7px;font-size:22px}.report-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:20px}.report-card h2{font-size:16px;margin:0 0 16px}.report-table{width:100%;border-collapse:collapse;font-size:13px}.report-table th,.report-table td{padding:11px 10px;text-align:left;border-bottom:1px solid #e4e9f1}.report-table th{background:#f5f7fb;color:#4a5568;font-size:10px;text-transform:uppercase}.report-table td:last-child,.report-table th:last-child{text-align:right}.badge{display:inline-block;padding:4px 7px;border-radius:4px;background:#e8f0fc;color:#174a9b;font-size:11px;font-weight:700;text-transform:uppercase}.expense-badge{background:#fde8e8;color:#9b2929}.empty{text-align:center;color:#78849a;padding:22px!important}@media(max-width:800px){.summary,.report-grid{grid-template-columns:1fr}.report-head{display:block}.report-actions{margin-top:16px}}@media print{body{background:#fff!important}.sidebar,.topbar,.back-link,.print-button{display:none!important}.main{margin-left:0!important;width:100%!important}.content{padding:0!important}.report-head{display:block;margin-bottom:18px}.summary{grid-template-columns:repeat(3,1fr);gap:8px}.summary-card,.report-card{break-inside:avoid;box-shadow:none;border:1px solid #999;padding:12px}.report-grid{gap:10px}.report-table th{background:#eee!important;color:#000}.report-table td,.report-table th{padding:7px}.badge{border:1px solid #777;background:#fff!important;color:#000!important}}
</style></head><body><div class="app"><aside class="sidebar"><?php include "../partials/sidebar.php"; ?></aside><main class="main"><header class="topbar"><div class="module-tag">Workspace / Finance / <b>Financial Reports</b></div><div class="top-user"><div class="avatar"><?=strtoupper(substr(user()['name'],0,2))?></div><?=htmlspecialchars(user()['name'])?></div></header><section class="content"><div class="report-head"><div><a class="back-link" href="<?=htmlspecialchars($dashboardLink)?>">← Back to dashboard</a><h1>Financial Reports</h1><p>Review collections, expenses and outstanding student balances.</p></div><div class="report-actions"><button class="print-button" type="button" onclick="window.print()">Print report</button></div></div>
<div class="summary"><div class="summary-card"><span>Total revenue</span><strong><?=money($grandRevenue)?></strong></div><div class="summary-card"><span>Total expenses</span><strong><?=money($grandExpenses)?></strong></div><div class="summary-card"><span>Net cash flow</span><strong style="color:<?=$netCashFlow>=0?'#17834b':'#bd4242'?>"><?=money($netCashFlow)?></strong></div></div>
<div class="report-grid"><section class="report-card"><h2>Payment Channels</h2><table class="report-table"><thead><tr><th>Method</th><th>Transactions</th><th>Total</th></tr></thead><tbody><?php if(!$channelSummary):?><tr><td class="empty" colspan="3">No payment records found.</td></tr><?php else:foreach($channelSummary as $channel):?><tr><td><span class="badge"><?=htmlspecialchars(ucfirst($channel['payment_method']))?></span></td><td><?=htmlspecialchars($channel['tx_count'])?></td><td><?=money($channel['total_amount'])?></td></tr><?php endforeach;endif;?></tbody></table></section><section class="report-card"><h2>Expense Categories</h2><table class="report-table"><thead><tr><th>Category</th><th>Entries</th><th>Total</th></tr></thead><tbody><?php if(!$expenseSummary):?><tr><td class="empty" colspan="3">No expense records found.</td></tr><?php else:foreach($expenseSummary as $expense):?><tr><td><span class="badge expense-badge"><?=htmlspecialchars($expense['category'])?></span></td><td><?=htmlspecialchars($expense['voucher_count'])?></td><td><?=money($expense['total_spent'])?></td></tr><?php endforeach;endif;?></tbody></table></section></div>
<section class="report-card"><h2>Outstanding Student Balances</h2><div style="overflow-x:auto"><table class="report-table"><thead><tr><th>Admission No.</th><th>Student</th><th>Course</th><th>Total billed</th><th>Total paid</th><th>Outstanding</th></tr></thead><tbody><?php if(!$debtors):?><tr><td class="empty" colspan="6">All active student accounts are paid in full.</td></tr><?php else:foreach($debtors as $debtor):$balance=(float)$debtor['total_billed']-(float)$debtor['total_paid'];?><tr><td><?=htmlspecialchars($debtor['id_no'])?></td><td><?=htmlspecialchars($debtor['name'])?></td><td><?=htmlspecialchars($debtor['course_code'])?></td><td><?=money($debtor['total_billed'])?></td><td><?=money($debtor['total_paid'])?></td><td style="font-weight:700;color:#bd4242"><?=money($balance)?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
</section></main></div></body></html>
