<?php
require_once "../config.php";
requireLogin();
if(!allowed(['finance'])){http_response_code(403);die("Access denied.");}
$search=trim($_GET['search']??'');
$studentProfile=null;
$statementLogs=[];
if($search!==''){
 $stmt=$pdo->prepare("SELECT s.student_id,s.id_no,s.name,s.status,c.course_name,c.course_code,c.duration_months,d.department_name,COALESCE((SELECT SUM(fs.amount) FROM fee_structure fs WHERE fs.course_id=s.course_id),0) AS total_billed,COALESCE((SELECT SUM(fp.amount_paid) FROM fee_payments fp WHERE fp.student_id=s.student_id AND fp.amount_paid>0),0) AS total_paid FROM students s JOIN courses c ON c.course_id=s.course_id LEFT JOIN departments d ON d.department_id=c.department_id WHERE s.id_no=? OR s.name LIKE ? LIMIT 1");
 $stmt->execute([$search,"%$search%"]);$studentProfile=$stmt->fetch();
 if($studentProfile){$log=$pdo->prepare("SELECT fp.payment_date,fp.receipt_no,fp.amount_paid,fp.payment_method,fs.fee_type,fs.academic_year,fs.semester FROM fee_payments fp JOIN fee_structure fs ON fs.fee_structure_id=fp.fee_structure_id WHERE fp.student_id=? ORDER BY fp.payment_date DESC,fp.payment_id DESC");$log->execute([$studentProfile['student_id']]);$statementLogs=$log->fetchAll();}
}
$dashboardLink='../'.user()['home'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/gif" href="<?=htmlspecialchars(appAssetPath('Images/logo.gif'))?>"><title>Student Statements | College ERP</title><link rel="stylesheet" href="../assets/css/style.css"><style>.back-link{display:inline-block;margin-bottom:12px;color:#174a9b;font-size:13px;font-weight:700}.search-box,.statement-card{background:#fff;border:1px solid #e4e9f1;border-radius:8px;padding:20px;margin-bottom:20px}.search-box{display:flex;gap:12px}.search-box input{flex:1;padding:11px;border:1px solid #cbd5e0;border-radius:6px}.button{border:0;border-radius:7px;padding:11px 16px;background:#174a9b;color:#fff;font-weight:700;cursor:pointer}.statement-table{width:100%;border-collapse:collapse}.statement-table th,.statement-table td{padding:11px;border-bottom:1px solid #e4e9f1;text-align:left}.statement-table th{background:#f5f7fb;color:#4a5568;font-size:11px;text-transform:uppercase}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:18px 0}.metric{background:#f5f7fb;border-radius:6px;padding:14px}.metric span{display:block;color:#78849a;font-size:11px;text-transform:uppercase}.metric strong{display:block;margin-top:5px;font-size:18px}@media(max-width:650px){.search-box,.metrics{display:block}.search-box input{width:100%;margin-bottom:10px}.metrics .metric{margin-bottom:10px}}
</style></head><body><div class="app"><aside class="sidebar"><?php include "../partials/sidebar.php";?></aside><main class="main"><header class="topbar"><div class="module-tag">Workspace / Finance / <b>Student Statements</b></div><div class="top-user"><div class="avatar"><?=strtoupper(substr(user()['name'],0,2))?></div><?=htmlspecialchars(user()['name'])?></div></header><section class="content"><a class="back-link" href="<?=htmlspecialchars($dashboardLink)?>">← Back to dashboard</a><h1>Student Statements</h1><p class="text-muted">Look up a student balance and payment history.</p><form class="search-box" method="get"><input name="search" value="<?=htmlspecialchars($search)?>" placeholder="Admission number or student name" required><button class="button" type="submit">Search</button></form><?php if($search!==''&&!$studentProfile):?><div class="alert danger">No student found.</div><?php endif;?><?php if($studentProfile):$balance=(float)$studentProfile['total_billed']-(float)$studentProfile['total_paid'];?><section class="statement-card"><h2><?=htmlspecialchars($studentProfile['name'])?></h2><p><?=htmlspecialchars($studentProfile['id_no'].' · '.$studentProfile['course_code'].' · '.$studentProfile['course_name'])?></p><div class="metrics"><div class="metric"><span>Total billed</span><strong><?=money($studentProfile['total_billed'])?></strong></div><div class="metric"><span>Total paid</span><strong><?=money($studentProfile['total_paid'])?></strong></div><div class="metric"><span>Balance</span><strong><?=money(max(0,$balance))?></strong></div></div><h3>Payment history</h3><div style="overflow-x:auto"><table class="statement-table"><thead><tr><th>Date</th><th>Receipt</th><th>Type</th><th>Method</th><th>Amount</th></tr></thead><tbody><?php if(!$statementLogs):?><tr><td colspan="5">No payment history found.</td></tr><?php else:foreach($statementLogs as $log):?><tr><td><?=htmlspecialchars($log['payment_date'])?></td><td><?=htmlspecialchars($log['receipt_no'])?></td><td><?=htmlspecialchars(ucfirst($log['fee_type']))?></td><td><?=htmlspecialchars(ucfirst($log['payment_method']))?></td><td><?=money($log['amount_paid'])?></td></tr><?php endforeach;endif;?></tbody></table></div></section><?php endif;?></section></main></div></body></html>
