<?php
require_once "../config.php";
requireLogin();
if(!allowed(['students'])){http_response_code(403);die("Access denied.");}
$st=$pdo->prepare("SELECT s.*,c.course_code,c.course_name FROM students s JOIN student_accounts sa ON sa.student_id=s.student_id JOIN courses c ON c.course_id=s.course_id WHERE sa.username=? LIMIT 1");
$st->execute([user()['username']]);$student=$st->fetch();
$payments=0;
if($student){$q=$pdo->prepare("SELECT COALESCE(SUM(amount_paid),0) FROM fee_payments WHERE student_id=?");$q->execute([$student['student_id']]);$payments=$q->fetchColumn();}
$notices=$pdo->query("SELECT COUNT(*) FROM notices WHERE target_audience IN ('all','students')")->fetchColumn();
$services=moduleServices('students',user()['role']);
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student Portal</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><div class="app"><aside class="sidebar"><?php include "../partials/sidebar.php";?></aside><main class="main"><header class="topbar"><div class="module-tag">Workspace / <b>Student Portal</b></div><div class="top-user"><div class="avatar"><?=strtoupper(substr(user()['name'],0,2))?></div><?=htmlspecialchars(user()['name'])?></div></header><section class="content"><div class="page-head"><div><p class="eyebrow">STUDENT PORTAL</p><h1>Welcome, <?=htmlspecialchars(user()['name'])?></h1><p>Access your student services.</p></div></div><div class="stats"><div class="stat"><span>Student ID</span><strong><?=htmlspecialchars($student['id_no']??'N/A')?></strong></div><div class="stat"><span>Course</span><strong><?=htmlspecialchars($student['course_code']??'N/A')?></strong></div><div class="stat"><span>Payment Total</span><strong><?=money($payments)?></strong></div><div class="stat"><span>Notices</span><strong><?=htmlspecialchars($notices)?></strong></div></div><div class="grid"><section class="card"><h2>Your Modules</h2><?php foreach($services as $s):?><a class="service" href="<?=htmlspecialchars($s['path'])?>"><div class="service-icon">◆</div><div><b><?=htmlspecialchars($s['label'])?></b><small><?=htmlspecialchars($s['description'])?></small></div></a><?php endforeach;?></section><section class="card"><h2>Account Information</h2><div class="service"><div><b><?=htmlspecialchars($student['name']??user()['name'])?></b><small><?=htmlspecialchars($student['course_name']??'Course information unavailable')?></small></div></div><div class="service"><div><b>Status</b><small><?=htmlspecialchars(ucfirst($student['status']??'Unknown'))?></small></div></div></section></div></section></main></div></body></html>
